apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - name: graphql
      protocol: TCP
      port: 4000
      targetPort: 4000
    - name: metrics
      protocol: TCP
      port: 2223
      targetPort: 2223
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-d
spec:
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      restartPolicy: Always
      containers:
        - envFrom:
            - configMapRef:
                name: gateway-env
          image: "krixlion/dev_forum-gateway:0.1.0"
          imagePullPolicy: IfNotPresent
          name: server
          ports:
            - name: graphql
              containerPort: 4000
            - name: metrics
              containerPort: 2223
          resources:
            limits:
              cpu: 20m
              memory: 150Mi
            requests:
              cpu: 5m
              memory: 80Mi
