apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate-gateway
spec:
  secretName: tls-secret-gateway
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - key encipherment
    - digital signature
  dnsNames:
    - "gateway-service"
  issuerRef:
    name: root-issuer
    kind: Issuer
