resources:
  - ../../base
  - dev-volume.yaml

namespace: dev

replicas:
  - name: gateway-d
    count: 1

images:
  - name: krixlion/dev_forum-gateway
    newName: krixlion/go-reflex-dlv
    newTag: latest

patches:
  - path: deployment-patches.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: gateway-d

  - path: service-patches.yaml
    target:
      version: v1
      kind: Service
      name: gateway-service

configMapGenerator:
  - name: gateway-env
    env: gateway.properties
